Feat/tests coverage
Kuzuru/notifier-bot pull request #12
Opened 2022-10-10 18:25 UTC by LairTengi

2022-10-11 09:03 UTC, Kuzuru requested changes

2022-10-11 09:03 UTC, Kuzuru commented on src/test/java/urfu/core/commands/VersionCommandTest.java
> +        // Берём Version
Мне кажется, что каждый раз пояснять, что мы берем команду во всех трех файлах не имеет необходимости в виду того, что здесь всё семантически ясно из команды: `commands.get(...)`

Прошу убрать эти комментарии во всех трех файлах

2022-10-11 09:03 UTC, Kuzuru commented on src/test/java/urfu/core/commands/VersionCommandTest.java
> +        Assertions.assertEquals(s, command.getInfo());
Отсутствует корректное форматирование по стандартам

2022-10-11 10:52 UTC, LairTengi commented on src/test/java/urfu/core/commands/VersionCommandTest.java
> +        // Берём Version
Солидарна с твоим мнением. Уберу.

2022-10-11 10:52 UTC, LairTengi commented on src/test/java/urfu/core/commands/VersionCommandTest.java
> +        Assertions.assertEquals(s, command.getInfo());
Поправлю. Спасибо

2022-10-12 16:35 UTC, Kuzuru approved these changes

2022-10-12 16:36 UTC, merged